### PR TITLE
.travis.yml: pin containerd version

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

@crosbymichael PTAL?

### CODE REVIEW

**Comment by crosbymichael** [comment]
Why?

**Comment by AkihiroSuda** [comment]
@crosbymichael 

- To make sure the AUFS plugin is compatible with the latest beta release
- To increase reproducibility of the tests. Without this, it would be extremely difficult to analyze future CI failures.

**Comment by crosbymichael** [comment]
Doesn't it pull master by default?

**Comment by AkihiroSuda** [comment]
Yes, it pulls master, and I consider that is the problem, as it decreases reproducibility.

If you dont like this PR, may I just write "tested with 1.0.0beta.1" to README?

**Comment by crosbymichael** [comment]
Maybe just not right now until we hit a 1.0.  Its good to tests against master to catch any changes.  Its also a pain to update N snapshotters each time containerd updates with a version.

We don't need anything in the readme pinning a version because that is the same problem as updating the travis file, he has to be updated everytime we have a release because it gets out of sync quickly.

**Pull request closed without merging**
