### PR TITLE
Skip plugin load on not support

### PR DESCRIPTION
**Pull request by crosbymichael**
This will allow the caller to handle supported errors.

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
@AkihiroSuda have you seen this error before?

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda have you seen this error before?

Do you mean the `err` from `supported()` or CI failure? (both seems new to me)

```
    --- FAIL: TestAufs/128LayersMount (0.17s)
    	<autogenerated>:1: unmount /tmp/snapshot-suite-Aufs-140115871/work/prepare-layer-0
    	<autogenerated>:1: unmount /tmp/snapshot-suite-Aufs-140115871/work/prepare-layer-1
    	<autogenerated>:1: unmount /tmp/snapshot-suite-Aufs-140115871/work/prepare-layer-2
    	<autogenerated>:1: unmount /tmp/snapshot-suite-Aufs-140115871/work/prepare-layer-3
    	testsuite.go:910: [layer 3] preparing doesn't equal to flat before apply: directory diff between /tmp/snapshot-suite-Aufs-140115871/work/prepare-layer-3 and /tmp/snapshot-suite-Aufs-140115871/work/flat
    		- /ONLYME/file-1
    		
    		github.com/containerd/containerd/vendor/github.com/containerd/continuity/fs/fstest.CheckDirectoryEqual
    			/home/travis/gopath/src/github.com/containerd/containerd/vendor/github.com/containerd/continuity/fs/fstest/compare.go:53
    		github.com/containerd/containerd/snapshots/testsuite.check128LayersMount
    			/home/travis/gopath/src/github.com/containerd/containerd/snapshots/testsuite/testsuite.go:908
    		github.com/containerd/containerd/snapshots/testsuite.makeTest.func1
    			/home/travis/gopath/src/github.com/containerd/containerd/snapshots/testsuite/testsuite.go:111
    		testing.tRunner
    			/home/travis/.gimme/versions/go1.9.7.linux.amd64/src/testing/testing.go:746
    		runtime.goexit
    			/home/travis/.gimme/versions/go1.9.7.linux.amd64/src/runtime/asm_amd64.s:2337
    	helpers.go:67: drwx------       4096 /tmp/snapshot-suite-Aufs-140115871
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/root
    	helpers.go:65: -rw-------      65536 /tmp/snapshot-suite-Aufs-140115871/root/metadata.db [ "\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\xed\xda\f\xed\x02\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\b\x00\x00\x00\x00\x00\x00\x00\x0e\x00\x00\x00\x00\x00\x00\x00" ...]
    	helpers.go:67: drwx------       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots
    	helpers.go:67: drwx------       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/1
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/1/fs
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/1/fs/ADDHERE
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/1/fs/ONLYME
    	helpers.go:65: -rwxrwxrwx          5 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/1/fs/ONLYME/bottom [ "bye!\n" ...]
    	helpers.go:65: -rwxrwxrwx         18 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/1/fs/bottom [ "way at the bottom\n" ...]
    	helpers.go:65: -rwxrwxrwx          7 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/1/fs/overwriteme [ "FIRST!\n" ...]
    	helpers.go:67: drwx------       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/2
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/2/fs
    	helpers.go:65: -r--r--r--          0 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/2/fs/.wh..wh.aufs [ "" ...]
    	helpers.go:67: drwx------       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/2/fs/.wh..wh.orph
    	helpers.go:67: drwx------       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/2/fs/.wh..wh.plnk
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/2/fs/ADDHERE
    	helpers.go:65: -rwxr-xr-x          5 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/2/fs/ADDHERE/file-1 [ "same\n" ...]
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/2/fs/ONLYME
    	helpers.go:65: -r--r--r--          0 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/2/fs/ONLYME/.wh..wh..opq [ "" ...]
    	helpers.go:65: -rwxrwxrwx          9 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/2/fs/ONLYME/file-1 [ "only me!\n" ...]
    	helpers.go:65: -rwxrwxrwx         12 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/2/fs/overwriteme [ "1 WAS HERE!\n" ...]
    	helpers.go:67: drwx------       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/3
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/3/fs
    	helpers.go:65: -r--r--r--          0 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/3/fs/.wh..wh.aufs [ "" ...]
    	helpers.go:67: drwx------       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/3/fs/.wh..wh.orph
    	helpers.go:67: drwx------       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/3/fs/.wh..wh.plnk
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/3/fs/ADDHERE
    	helpers.go:65: -rwxr-xr-x          5 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/3/fs/ADDHERE/file-2 [ "same\n" ...]
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/3/fs/ONLYME
    	helpers.go:65: -r--r--r--          0 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/3/fs/ONLYME/.wh..wh..opq [ "" ...]
    	helpers.go:65: -rwxrwxrwx          9 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/3/fs/ONLYME/file-2 [ "only me!\n" ...]
    	helpers.go:65: -rwxrwxrwx         12 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/3/fs/overwriteme [ "2 WAS HERE!\n" ...]
    	helpers.go:67: drwx------       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/4
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/4/fs
    	helpers.go:65: -r--r--r--          0 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/4/fs/.wh..wh.aufs [ "" ...]
    	helpers.go:67: drwx------       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/4/fs/.wh..wh.orph
    	helpers.go:67: drwx------       4096 /tmp/snapshot-suite-Aufs-140115871/root/snapshots/4/fs/.wh..wh.plnk
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/work
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/work/flat
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/work/flat/ADDHERE
    	helpers.go:65: -rwxr-xr-x          5 /tmp/snapshot-suite-Aufs-140115871/work/flat/ADDHERE/file-1 [ "same\n" ...]
    	helpers.go:65: -rwxr-xr-x          5 /tmp/snapshot-suite-Aufs-140115871/work/flat/ADDHERE/file-2 [ "same\n" ...]
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/work/flat/ONLYME
    	helpers.go:65: -rwxrwxrwx          9 /tmp/snapshot-suite-Aufs-140115871/work/flat/ONLYME/file-2 [ "only me!\n" ...]
    	helpers.go:65: -rwxrwxrwx         18 /tmp/snapshot-suite-Aufs-140115871/work/flat/bottom [ "way at the bottom\n" ...]
    	helpers.go:65: -rwxrwxrwx         12 /tmp/snapshot-suite-Aufs-140115871/work/flat/overwriteme [ "2 WAS HERE!\n" ...]
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/work/prepare-layer-0
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/work/prepare-layer-1
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/work/prepare-layer-2
    	helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-Aufs-140115871/work/prepare-layer-3
```

**Comment by crosbymichael** [comment]
I have to skip this test for AUFS in the containerd tests,

**Review by estesp — APPROVED** [review]
LGTM

**Comment by dmcgowan** [comment]
LGTM

**Pull request merged**
