### PR TITLE
Added filters to Walk method signature

### PR DESCRIPTION
**Pull request by Zyqsempai**
Signed-off-by: bpopovschi <zyqsempai@mail.ru>
Related to https://github.com/containerd/containerd/pull/3709
Fixed Walk method signature to correspond new interface defined in containerd

### CODE REVIEW

**Comment by fuweid** [comment]
ping @Zyqsempai

containerd/containerd#3709 has been merged, could you please to update your pr? thanks

**Comment by Zyqsempai** [comment]
@fuweid Done.

**Review by AkihiroSuda — APPROVED** [review]

**Review by fuweid — APPROVED** [review]
LGTM

**Comment by fuweid** [comment]
@Zyqsempai Thanks!

**Pull request merged**
